### ISSUE TITLE
Can't configure card

### ISSUE THREAD

**Issue by deltagolf** [LedgerHQ/ledger-app-openpgp-card#18]
Are there any issues with the openpgp card app after the last firmware update to the ledger nano s? I can generate passwords and sign documents with it, but I fail to even get a card-status update. Everytime I try I get a message like this:

```
DIEGOs-Mac-Pro:~ diego$ gpg --card-status
gpg: selecting openpgp failed: Operation not supported by device
gpg: tarjeta OpenPGP no disponible: Operation not supported by device
```

**Comment by thibaultamartin** [comment]
As mentioned in issue #21 I am facing the same issue, as of April 16th

**Comment by shubhamy** [comment]
Any update on this?

**Comment by cslashm** [comment]
I need more info. Any log?

**Comment by atishnazir** [comment]
Just started trying to charactorise the issue.

Using pcsc_scan v1.5.2 (from [MacPorts](https://www.macports.org/)), justs spins indefinitely:

``
pcsc_scan
PC/SC device scanner
V 1.5.2 (c) 2001-2017, Ludovic Rousseau <ludovic.rousseau@free.fr>
Plug'n play reader name not supported. Using polling every 1000 ms.
Scanning present readers...
Waiting for the first reader... |
``

Increasing the log level within `/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle/Contents/Info.plist` has no effect within dmesg and Console:

``
        <key>ifdLogLevel</key>
        <string>0x0003</string>
``

A quick check within System Information shows that the USB attributes are unchanged and correspond to Info.plist:

<img width="309" alt="screen shot 2018-06-15 at 08 55 05" src="https://user-images.githubusercontent.com/29478280/41456928-f01516c4-7079-11e8-8928-381d30647d80.png">


Other applications on the Ledger continue to work fine on the Mac, tested: U2F ID and BitCoin.  Interestingly spinning up a VMWare on the same MBP and assigning the Ledger to that.  I'm able to perform OpenPGP operations.   Suggests a strange interaction below ccid on MacOS.

**Comment by atishnazir** [comment]
With a Ledger plugged in, expected to see it at the bottom of list:

```
system_profiler SPSmartCardsDataType
SmartCards:

    Readers:

    Reader Drivers:

      #01: org.debian.alioth.pcsclite.smartcardccid:1.4.27 (/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle)

    Tokend Drivers:

    SmartCard Drivers:

      #01: com.apple.CryptoTokenKit.pivtoken:1.0 (/System/Library/Frameworks/CryptoTokenKit.framework/PlugIns/pivtoken.appex)

    Available SmartCards (keychain):

    Available SmartCards (token):
```

**Comment by kaspersoerensen** [comment]
Same here. Followed same configuration as in #21. Running ``system_profiler SPSmartCardsDataType`` gives same output as @atishnazir. Running ``pcsctest`` outputs 
```
MUSCLE PC/SC Lite Test Program

Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange
Please insert a working reader   :
```
But never completes as it cannot find the ledger nano s.

**Comment by mhhf** [comment]
I've the same issue. Everything works on the ledger firmware 1.4.1 + app v1.1.0 but fails on firmware 1.4.2 + app v1.2.1 on the same machine.
Any Ideas how to debug this @cslashm ?

**Comment by luginbash** [comment]
I'm having exactly the same problem here.

**Comment by savenas** [comment]
You need to have the latest drivers for Ledger Nano S
org.debian.alioth.pcsclite.smartcardccid:1.4.30 
```
system_profiler SPSmartCardsDataType
SmartCards:

    Readers:

      #01: Ledger Nano S (ATR:<3b00>)

    Reader Drivers:

      #01: org.debian.alioth.pcsclite.smartcardccid:1.4.27 (/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle)
      #02: org.debian.alioth.pcsclite.smartcardccid:1.4.30 (/usr/local/libexec/SmartCardServices/drivers/ifd-ccid.bundle)
```
I made a tutorial for GPG tools, Ledger nano S and Mojave.
Please follow the link below:
https://github.com/savenas/docs/blob/master/gpg_ledger_mojave.md

**Comment by kaspersoerensen** [comment]
Cool @savenas - Will try that out asap.

**Comment by imbenwolf** [comment]
> You need to have the latest drivers for Ledger Nano S
> org.debian.alioth.pcsclite.smartcardccid:1.4.30
> 
> ```
> system_profiler SPSmartCardsDataType
> SmartCards:
> 
>     Readers:
> 
>       #01: Ledger Nano S (ATR:<3b00>)
> 
>     Reader Drivers:
> 
>       #01: org.debian.alioth.pcsclite.smartcardccid:1.4.27 (/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle)
>       #02: org.debian.alioth.pcsclite.smartcardccid:1.4.30 (/usr/local/libexec/SmartCardServices/drivers/ifd-ccid.bundle)
> ```
> 
> I made a tutorial for GPG tools, Ledger nano S and Mojave.
> Please follow the link below:
> https://github.com/savenas/docs/blob/master/gpg_ledger_mojave.md

Hi, the link is not accessible anymore. Do you mind adding the instructions here? I'm sure others like me still have the same issue... Thanks!

**Comment by bereska** [comment]
@savenas your tutorial is unavailable any more? I am struggling to install 1.4.30 driver to my mac to detect Nano X as smart card

**Comment by bereska** [comment]
@cslashm bonjour, unfortunately even with the latest `#01: org.debian.alioth.pcsclite.smartcardccid:1.4.32 (/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle)` installed on mac os Catalina my ledger nano x is still undetectable as a smart card in OpenPGP app mode. When will we have a natural support for ledger smart card on mac os? it's been three years and the issue is still not solved. Merci

**Comment by philihp** [comment]
I'd love to see this happen, perhaps with Big Sur? It could make obsolete the SSH Ledger app, as GnuPG can run as an agent.

**Comment by bereska** [comment]
@philihp I ended up spinning up an ubuntu in virtualbox on my macbook air and setting up my ledger nano x with OpenPGP app there. So now I have both https://github.com/romanz/trezor-agent SSH/GPG app running natively on mac os and Ledger OpenPGP app running in the virtual machine. Both have been tested positive in delete and restore mode on nano x

**Comment by pinutz23** [comment]
Why is this closed? The problem seems to still exsits..

**Comment by Lohann** [comment]
Same issue here on MacOS Big Sur 11.4 and gpg (GnuPG) 2.3.1
```
~ gpg --card-status
gpg: selecting card failed: Operation not supported by device
gpg: OpenPGP card not available: Operation not supported by device
```

**Comment by ftpmorph** [comment]
Issue still persists on macOS Big Sur 11.6.1 using GnuPG 2.2.32 (the latest version at the time of writing). I also have the correct driver org.debian.alioth.pcsclite.smartcardccid:1.4.32 and libusb 1.0.24 is installed and up to date according to brew.

Tried both a Nano S and Nano X and the OpenPGP and OpenPGP.XL apps. Firmware on both Ledgers is up to date as were the apps.

Just like everyone else I am still getting the same error no matter what when running commands from gpg, including after setting GNUPGHOME to the "ledger" directory:

> gpg --card-status  
> gpg: selecting card failed: Operation not supported by device  
> gpg: OpenPGP card not available: Operation not supported by device  

However... using the Python scripts I was able to successfully run:

> ledger-gpg init "Name <email@domain.tld>" -e ed25519 -v

On my Nano X, and when I used the ~/.gnupg/ledger directory as GNUPGHOME running `gpg -K` listed only the new PGP key I just generated.

So it's not fully unable to connect, something is working somewhere, the Ledger is just not able to connect to the `gpg-agent` so commands are not passed through `gpg` (`gpg -K` worked because it just reads the keychain db, and I changed the environment variable to point it at the Ledger one stored in my home folder, it still won't interact with the Ledger).

I believe there is a config you can put into `gpg.conf` that lets you point it to a different agent, and if you point it to the path of `ledger-gpg-agent` that might fix it. I don't want to risk losing my existing keychain though so I just undid all the changes and left it.

This has pushed me to look into Yubikey and similar devices though, if they have a functional USB interface instead of all this mess they certainly seem very useful for security. Shame I couldn't use the device I already have though.

**Comment by JannikWempe** [comment]
I am with @ftpmorph here. Unfortunately the not working gpg forces me to have a look an YubiKey 😕
